### PR TITLE
Added file (courtesy Josh) to prepare compound stocks

### PR DESCRIPTION
**Pull request by pgrinaway**

### CODE REVIEW

**Comment by pgrinaway** [comment]
Going to take a look now

**Comment by pgrinaway** [comment]
LGTM. I'm going to merge this.

**Comment by jchodera** [comment]
Awesome!  It looks like you even used the molecule weights of the salt forms---is that right?

The purifies may also need to be taken into account.

**Comment by pgrinaway** [comment]
Yeah, I went and grabbed the Mws of the salts we have. Good point about the purities.

**Pull request merged**
